config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root 'static_pages#home'
  get '/search', to: 'static_pages#search'
  get'/new', to: 'static_pages#new'

  devise_for :users , controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:index, :show]
  resources :films do
    get :view, on: :member
    collection do
      get :filter
      get :top_movie
    end
    resources :comments, only: [:create, :destroy, :edit]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, class_name: User.name
  belongs_to :rateable, polymorphic: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :film
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :film
  has_many :link_episodes

  def link_exist?
    link_episodes.any?
  end

  def get_link(quality=0)
    link_by_quality = link_episodes.find_by(quality: quality)
    if link_by_quality.present?
      link_by_quality.link
    else
      link_episodes.last.link
    end
  end
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :film
end

app/models/film.rb
class Film < ApplicationRecord
  ratyrate_rateable :rate
  has_many :episodes

  has_many :film_genres
  has_many :genres, through: :film_genres

  has_many :film_origins
  has_many :origins, through: :film_origins

  has_many :comments
  has_many :ratings

  scope :movie, -> { where("num_ep = 1") }
  scope :tv_series, -> { where("num_ep > 1") }

  scope :category, -> (category) {
    case category
    when Settings.film.movie
      movie
    when Settings.film.tv_series
      tv_series
    end
  }

  scope :top_view, ->{order("num_view DESC")}
  scope :top_updated, ->{order("created_at DESC")}
  scope :top_comment, ->{order("comment_count DESC")}
  scope :top_rate, ->{order("rate_point DESC")}
  scope :top_movie_by, ->(type){
    case type
    when "top_view"
      top_view
    when "lastest_trailer"
      top_updated
    when "top_rated"
      top_rate
    when "top_comment"
      top_comment
    end
  }

  scope :genre, ->(genre_id) {joins(:genres).where "genres.id IN (?)", genre_id}
  scope :origin, ->(origin_id) {joins(:origins).where "origins.id IN (?)", origin_id}

  def self.update_comment_and_rating!
    self.find_in_batches do |films|
      sleep(5)
      films.each do |film|
        film.update_attributes(comment_count: film.comment_cal, rate_point: film.rate_cal)
      end
    end
  end

  def comment_cal
  	comments.count
  end

   def movie?
    num_ep == Settings.film.movie.to_i
  end

  def rate_cal
  	average(:rate).present? ? average(:rate).avg : 0
  end
end

app/models/film_genre.rb
class FilmGenre < ApplicationRecord
  belongs_to :film
  belongs_to :genre
end

app/models/film_origin.rb
class FilmOrigin < ApplicationRecord
  belongs_to :film
  belongs_to :origin
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :film_genres
  has_many :films, through: :film_genres
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user
  belongs_to :film
end

app/models/link_episode.rb
class LinkEpisode < ApplicationRecord
  belongs_to :episode
  enum quality: {low: 1, medium: 2, high: 3}
end

app/models/origin.rb
class Origin < ApplicationRecord
  has_many :film_origins
  has_many :films, through: :film_origins
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, polymorphic: true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, class_name: User.name
  belongs_to :rateable, polymorphic: true
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, polymorphic: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user_1, class_name: User.name
  belongs_to :user_2, class_name: User.name
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :film
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :confirmable,:registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers:%i[facebook]

  ratyrate_rater

  has_many :comments, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :histories, dependent: :destroy
  has_many :favourites, dependent: :destroy

  has_many :watched_films, through: :histories, source: :film
  has_many :favourite_films, through: :histories, source: :film

  scope :created_sort, ->{order created: :desc}

  def friends
    Relation.where(user1_id: self.id).or(Relation.where(user2_id: self.id))
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.confirmed_at = Time.now
      user.confirmation_token = nil
      #user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  skip_before_action :authenticate_user!

  def index; end

  def filter
    filter_films = Film.all
    filter_params.each do |key, val|
      filter_films.merge!(filter_films.send(key, val)) if (Film.respond_to? key) && (val.present?)
    end
    @category = [["Movie", "1"], ["TV_series", "2"]]
    @selected_params = filter_params
    @films = filter_films.paginate(page: params[:page],
                                    per_page: Settings.film.per_page)
  end

  def top_movie
    @top_movies = Film.top_movie_by(params[:type]).paginate(page: params[:page], per_page: 10)
    # @top_movies = top_movie.
  end

  def show
    @film = Film.find_by id: params[:id]
    redirect_to root_url unless @film
    @avg_rating = @film.rate_cal
    @comments = @film.comments.order("created_at DESC").paginate(page: params[:page], per_page: 10)
  end

  def view
    @film = Film.find_by id: params[:id]
    redirect_to root_url unless @film
    @episodes = @film.episodes.order("num_epi ASC")

    @episode = params[:episode_id] ? @episodes.find_by(id: params[:episode_id]) : @episodes.first
    redirect_to view_film_path(@film) unless @episodes.include? @episode
  end

  private
  def filter_params
    params.permit(:origin, :genre, :category)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.email, class: "gravatar")
  end
end

app/views/films/_film.html.erb
<div class="movie">
  <div class="movie-image"> <span class="">
  </span> <%= link_to "#{image_tag(film.img)}".html_safe , film_path(film) %> </div>
  <span class="name">
  <%= film.name %>
  </span>
  <div class="rating">
    <p><%= t".rating"%></p>
    <div class="stars">
      <div class="stars-in"> </div>
    </div>
    <span class="comments">12</span> </div>
</div>

app/views/films/filter.html.erb
<%= form_tag filter_films_path, method: "get" do %>
  <%= select_tag "category", options_for_select(@category, @selected_params[:category]),
                                                prompt: "Category" %>
  <%= select_tag "origin", options_from_collection_for_select(@origins, :id, :name, @selected_params[:origin]),
                                                prompt: "Origins" %>
  <%= select_tag "genre", options_from_collection_for_select(@genres, :id, :name, @selected_params[:genre]),
                                                prompt: "Genres" %>
  <%= submit_tag "Filter", name: nil %>
<% end %>
<div class="box">
  <div class="head">
    <% if @films %>
      <% @films.each do |film| %>
        <%= render partial: "film", locals: { film: film } %>
      <% end %>
      <div class="cl">&nbsp;</div>
      <%= will_paginate @films %>
    <%end%>
  </div>
</div>

app/views/films/show.html.erb
<div id="DIV_1">
<div id="DIV_2">
  <div id="DIV_3">
    <div id="DIV_4">
      <div id="DIV_5">
        <h1 id="H1_6">
          <span id="SPAN_7">
          <a href="" id="A_8">
            <%= @film.alter_name %>
          </a></span>
          <span id="SPAN_9">
            <%= @film.name%>
          </span>
        </h1>
        <div id="DIV_11">
          <div id="DIV_12">
            <dl id="DL_13">
                Số người đánh giá:
              </dt>
              <dt id="DT_26">
                Quốc gia:
              </dt>
              <dd id="DD_27">
                <% @film.origins.each do |origin| %>
                     <%= link_to origin.name , filter_films_path(origin: origin.id), id: "A_28" %>
                <%end%>
              </dd><br id="BR_29" />
              <dt id="DT_30">
                Năm:
              </dt>
              <dd id="DD_31">
                <a title="Phim mới 2018" href="phim-2018/" id="A_32">
                  <%= @film.copyright_year %>
                </a>
              </dd><br id="BR_33" />
              <dt id="DT_34">
                Ngôn ngữ:
              </dt>
              <dd id="DD_47">
                Phụ đề Việt
              </dd><br id="BR_48" />
              <dt id="DT_49">
                Thể loại:
              </dt>
              <dd id="DD_50">
                <% @film.genres.each do |genres| %>
                <a href="the-loai/phim-kinh-di/" title="Phim kinh dị" id="A_51">
                  <%= genres.name %> ,
                </a>
                <%end%>
              </dd><br id="BR_54" />
              <div class='star-rating' data-score=<%= @avg_rating %>></div>
              <dt id="DT_58">
                Lượt xem:
              </dt>
              <dd id="DD_59">
                19,152
              </dd>
            </dl>
            <div id="DIV_60">
            </div>
          </div>
          <div id="DIV_61">
          </div>
          <div id="DIV_62">
          </div>
        </div>
        <div id="DIV_63">
          Rate this film  : <%= rating_for @film, 'rate' %>
          <span id="SPAN_80"></span>
          <div id="IMG_83" >
          <%= image_tag(@film.img) %>
          </div>
          <div id="IMG_84" >
          <%= image_tag (@film.img)%>
          </div>
          <span id="SPAN_85">
          <span id="SPAN_86">10
          </span>
          </span>
          <meta content="10" id="META_87" />
          <meta content="2" id="META_88" />
          <div id="DIV_89">
            <span id="SPAN_90"></span>

          </div>
        </div>
      </div>
      <div id="DIV_92">
        <div id="DIV_93">
          <div id="IMG_94">
          <%= image_tag(@film.img) %>
          </div>
          <h2 id="H2_95">
            Xem phim
          </h2>
          <ul id="UL_96">
            <li id="LI_97">
              <%= link_to  "Download", "#", id: "A_98" %>
            </li>
            <li id="LI_99">
              <%= link_to  "Report", "#", id: "A_100" %>
            </li>
            <li id="LI_101">
            <%= link_to  "View", view_film_path(@film), id: "A_102" %>
            </li>
          </ul>
        </div>
        <!-- Bookmark-->

        <div id="DIV_103">
          <div id="DIV_104">
            <span id="SPAN_105"></span><span id="SPAN_106"></span>
          </div>
        </div>
        <!-- // Bookmark-->

        <div id="DIV_107">
          <div id="DIV_108">
            <button type="button" id="BUTTON_109">
              <span id="SPAN_110"></span>
            </button>
            <ul id="UL_111">
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="DIV_112">
    <!-- uniAd Code zone 118-Dưới nút xem phim/phimmoi.net -->

    <!-- uniAd Code zone 118-Dưới nút xem phim/phimmoi.net -->

  </div>

  <article id="ARTICLE_189">
      <h2 id="H2_190">
        Nội dung phim
      </h2>
      <div id="DIV_191">
        <span id="SPAN_192"></span>

      </div>
      <div id="DIV_194">
        <p id="P_195">
          <%= @film.description %>
        </p>
      </div>
    </article>
</div>
<!-- / Thông tin phim -->

<div id="DIV_204">
  <h4 id="H4_205">
    Bình luận về phim
  </h4>
  <div id="DIV_206">
    <%= javascript_include_tag 'ratyrate.js', "data-turbolinks-track": false %>
    <% if user_signed_in? %>
    <div>
      <%= render partial:"comments/form_cmt" %>
    </div>
    <%end%>
    <div>
      <%= render @comments %>
      <%= will_paginate @comments %>
    </div>
  </div>
</div>

app/views/films/top_movie.html.erb
<div class="box">
  <div class="head">
    <% if @top_movies.any? %> 
      <% @top_movies.each do |film| %>
        <%= render partial: "films/film", locals: { film: film } %>
      <% end %>  
      <div class="cl">&nbsp;</div>
      <%= will_paginate @top_movies %>
    <%end%>
  </div>
</div>

app/views/films/view.html.erb
<div class="film-container" >
  <div id="film-name">
    <%= @film.name %>
  </div>
  <% if @episode.link_exist? %>
    <div class="video-container">
      <%= video_tag @episode.get_link(params[:link_quality]), controls: true, height: 500 %>
    </div>
    <div class="quality">
      <% @episode.link_episodes.each do |link| %>
        <%= link_to link.quality, view_film_path(@film, episode_id: @episode.id,
                                                         quality: link.quality) %>
      <% end %>
    </div>

  <% else %>
    <%= t ".link_not_exist" %>
  <% end %>

  <% unless @film.movie? %>
    <%= t ".list_of_episodes" %>
    <div class="tv_series">
      <% @episodes.each do |episode| %>
        <%= link_to episode.num_epi, view_film_path(@film, episode_id: episode.id) %>
      <% end %>
    </div>
  <% end %>
<div>