config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root 'static_pages#home'
  get '/search', to: 'static_pages#search'
  get'/new', to: 'static_pages#new'

  devise_for :users , controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:index, :show]
  resources :films do
    get :view, on: :member
    collection do
      get :filter
      get :top_movie
    end
    resources :comments, only: [:create, :destroy, :edit]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
  end
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, class_name: User.name
  belongs_to :rateable, polymorphic: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :film
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :film
  has_many :link_episodes

  def link_exist?
    link_episodes.any?
  end

  def get_link(quality=0)
    link_by_quality = link_episodes.find_by(quality: quality)
    if link_by_quality.present?
      link_by_quality.link
    else
      link_episodes.last.link
    end
  end
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :film
end

app/models/film.rb
class Film < ApplicationRecord
  ratyrate_rateable :rate
  has_many :episodes

  has_many :film_genres
  has_many :genres, through: :film_genres

  has_many :film_origins
  has_many :origins, through: :film_origins

  has_many :comments
  has_many :ratings

  scope :movie, -> { where("num_ep = 1") }
  scope :tv_series, -> { where("num_ep > 1") }

  scope :category, -> (category) {
    case category
    when Settings.film.movie
      movie
    when Settings.film.tv_series
      tv_series
    end
  }

  scope :top_view, ->{order("num_view DESC")}
  scope :top_updated, ->{order("created_at DESC")}
  scope :top_comment, ->{order("comment_count DESC")}
  scope :top_rate, ->{order("rate_point DESC")}
  scope :top_movie_by, ->(type){
    case type
    when "top_view"
      top_view
    when "lastest_trailer"
      top_updated
    when "top_rated"
      top_rate
    when "top_comment"
      top_comment
    end
  }

  scope :genre, ->(genre_id) {joins(:genres).where "genres.id IN (?)", genre_id}
  scope :origin, ->(origin_id) {joins(:origins).where "origins.id IN (?)", origin_id}

  def self.update_comment_and_rating!
    self.find_in_batches do |films|
      sleep(5)
      films.each do |film|
        film.update_attributes(comment_count: film.comment_cal, rate_point: film.rate_cal)
      end
    end
  end

  def comment_cal
  	comments.count
  end

   def movie?
    num_ep == Settings.film.movie.to_i
  end

  def rate_cal
  	average(:rate).present? ? average(:rate).avg : 0
  end
end

app/models/film_genre.rb
class FilmGenre < ApplicationRecord
  belongs_to :film
  belongs_to :genre
end

app/models/film_origin.rb
class FilmOrigin < ApplicationRecord
  belongs_to :film
  belongs_to :origin
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :film_genres
  has_many :films, through: :film_genres
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user
  belongs_to :film
end

app/models/link_episode.rb
class LinkEpisode < ApplicationRecord
  belongs_to :episode
  enum quality: {low: 1, medium: 2, high: 3}
end

app/models/origin.rb
class Origin < ApplicationRecord
  has_many :film_origins
  has_many :films, through: :film_origins
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, polymorphic: true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, class_name: User.name
  belongs_to :rateable, polymorphic: true
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, polymorphic: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user_1, class_name: User.name
  belongs_to :user_2, class_name: User.name
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :film
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :confirmable,:registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers:%i[facebook]

  ratyrate_rater

  has_many :comments, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :histories, dependent: :destroy
  has_many :favourites, dependent: :destroy

  has_many :watched_films, through: :histories, source: :film
  has_many :favourite_films, through: :histories, source: :film

  scope :created_sort, ->{order created: :desc}

  def friends
    Relation.where(user1_id: self.id).or(Relation.where(user2_id: self.id))
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.confirmed_at = Time.now
      user.confirmation_token = nil
      #user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.email, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer id="footer">
  <p class="lf"><%= t".nguon"%><a href="#"><%=t".site_name"%></a><%=t".reserved"%></p>
  <p class="rf"><%= t".design_by"%> <a href="http://chocotemplates.com/"><%=t".link_theme"%></a></p>
  <div style="clear:both;"></div>
</footer>

app/views/layouts/_header.html.erb
<header id="header">
    <h1 id="logo"><%=link_to (t ".movie_hunter"), root_path%></h1>
    <div class="social"> <span><%= t".follow" %></span>
      <ul>
        <li><a class="twitter" href="#">twitter</a></li>
        <li><a class="facebook" href="#">facebook</a></li>
        <li><a class="vimeo" href="#">vimeo</a></li>
        <li><a class="rss" href="#">rss</a></li>
      </ul>
    </div>
    <div id="navigation">
      <ul>
        <li><a class="active"><%= link_to (t ".home") ,root_path%></a></li>
        <li><%= link_to (t".new"), new_path%></li>
        <li><%= link_to (t".theaters")  %></li>
        <li><%= link_to (t".coming_soon") %></li>
        <li><%= render 'devise/menu/registration_items' %></li>
        <li><%= render 'devise/menu/login_items' %></li>
        <li><%= link_to "USERS", users_path %></li>
      </ul>
    </div>
    <div id="sub-navigation">
      <ul>
        <li>
           <%= link_to (t ".movie"), filter_films_path(category: Settings.film.movie) %>
        </li>
        <li>
           <%= link_to (t ".tv_series"), filter_films_path(category: Settings.film.tv_series) %>
        </li>

        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= (t ".origin") %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% @origins.each do |origin| %>
                <li><%= link_to origin.name, filter_films_path(origin: origin.id) %></li>
              <% end %>
              <li class="divider"></li>
            </ul>
          </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= (t ".genre") %>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <% @genres.each do |genre| %>
              <li><%= link_to genre.name, filter_films_path(genre: genre.id) %></li>
            <% end %>
            <li class="divider"></li>
          </ul>
        </li>
      </ul>
      <div id="search">
        <%= search_form_for @q, url: search_path do |f| %>
          <%= f.label :name_or_alter_name_cont %>
          <%= f.search_field :name_or_alter_name_cont %>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Pr1702MovieOnline</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<title>MovieHunter</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>
<div id="shell">
	<%= render 'layouts/header' %>
	<%= yield %>
	<%= render 'layouts/footer' %>
	</div>
</body>
</html>